Refactoring
milaboratory/milib pull request #109
Opened 2022-12-12 08:52 UTC by gnefedev

2022-12-13 19:26 UTC, dbolotin requested changes

2022-12-13 19:26 UTC, dbolotin commented on src/main/kotlin/com/milaboratory/util/CachedPipe.kt
> +    val tempFile = tempDest.resolvePath("tempFile." + ThreadLocalRandom.current().nextInt())
Better have some fixed size random string generator. With int: low entropy per character, and negative values.

2022-12-13 19:26 UTC, dbolotin commented on src/main/kotlin/com/milaboratory/util/CachedPipe.kt
> +    function: (() -> OutputPort<T>) -> R
You may return the `OutputPortFactory` here, this will look better, and will be more compatible with other patterns that we currently have, or will add in the future. It has it's own `close` to perform cleanup, so, something like this will substitute current use-cases:
```
OutputPort<T>.cached(...).use{ factory -> ... }
```

I also suggest renaming it to `replayable`.

Last suggestion is running a dedicated thread here to write and buffer records for the consumer, to make sure original ordering is preserved.

2022-12-13 19:26 UTC, dbolotin commented on src/main/kotlin/com/milaboratory/util/CountLimitingOutputPort.kt
> +    override val currentIndex: Long
It is fine to have `count` and `currentIndex` returning the same value, readability is important.

2022-12-13 19:26 UTC, dbolotin commented on src/main/kotlin/com/milaboratory/util/GroupByPipe.kt
> +): OutputPort<List<T>> where R : Comparable<R>, R : Any = sortByHashOnDisk(
Maybe it is better to return `OutputPort` and leave the memory-expansive decision to the user of the method? I mean, whole input may fit into a single group.

2022-12-14 08:46 UTC, gnefedev commented on src/main/kotlin/com/milaboratory/util/CachedPipe.kt
> +    val tempFile = tempDest.resolvePath("tempFile." + ThreadLocalRandom.current().nextInt())
ok

2022-12-14 15:58 UTC, dbolotin approved these changes

2022-12-14 18:53 UTC, dbolotin approved these changes

2022-12-14 19:20 UTC, merged